version: "3.9"
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      PORT: "8000"
      K_SERVICE: "local"
      K_CONFIGURATION: "local"
      K_REVISION: "local-00001"
